name: ModernSky
softdepend: [CS-CoreLib, PlayerPoints]
main: me.masonic.mc.Core

version: 0.2.3

commands:
  mskyvip:
    description: vip
    usage: /mskyvip
  mskydr:
    description: DailyReward
    usage: /mskydr
  mskymsg:
    description: Message
    usage: /mskymsg
  mskysf:
    description: Slimefun
    usage: /mskysf
  mskysign:
    description: Sign
    usage: /mskysign
  mskybs:
    description: BlackShop
    usage: /mskybs
  mskyaa:
    description: AdvancedAbility
    usage: /mskyaa
  mskypac:
    description: Package
    usage: /mskypac
  mskypri:
    description: Privilege
    usage: /mskypri
permissions:
  msky.package.a:
    description: Access to all package A privileges
    children:
      msky.privilege.exp: true
      msky.privilege.backpack: true
      msky.privilege.ability: true