name: ModernSky

main: me.masonic.mc.Core

version: 1.0

commands:
  mskyvip:
    description: vip
    usage: /mskyvip
  mskydr:
    description: DailyReward
    usage: /mskydr
  mskymsg:
    description: Message
    usage: /mskymsg