name: ModernSky
softdepend: [CS-CoreLib, PlayerPoints]
main: me.masonic.mc.Core

version: 1.0

commands:
  mskyvip:
    description: vip
    usage: /mskyvip
  mskydr:
    description: DailyReward
    usage: /mskydr
  mskymsg:
    description: Message
    usage: /mskymsg
  mskysf:
    description: Slimefun
    usage: /mskysf
  mskysign:
    description: Sign
    usage: /mskysign
  mskybs:
    description: BlackShop
    usage: /mskybs
  mskyaa:
    description: AdvancedAbility
    usage: /mskyaa